// product/ui/src/Management.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import { api, type Source, type Job, type Status } from "./api";
  export let view: string;
  export let tick: number;
  export let status: Status;
  export let refresh: () => Promise<void>;
  export let logout: () => Promise<void>;
  let sources: { items: Source[]; allowed_roots: string[] } | null = null;
  let jobs: Job[] | null = null,
    settings: Record<string, unknown> | null = null;
  let path = "",
    error = "",
    message = "",
    busy = false,
    remove: Source | null = null,
    confirmDialog: HTMLDialogElement;
  let version = 0,
    alive = true;
  onDestroy(() => {
    alive = false;
    version++;
  });
  $: load(view, tick);
  $: if (remove && confirmDialog && !confirmDialog.open)
    confirmDialog.showModal();
  async function load(page: string, _tick: number) {
    const v = ++version;
    try {
      if (page === "Sources") {
        const result = await api<NonNullable<typeof sources>>("/sources");
        if (alive && v === version) sources = result;
      } else if (page === "Activity") {
        const result = await api<{ items: Job[] }>("/jobs");
        if (alive && v === version) jobs = result.items;
      } else {
        const result = await api<Record<string, unknown>>("/settings");
        if (alive && v === version) settings = result;
      }
    } catch (e) {
      if (alive && v === version) error = (e as Error).message;
    }
  }
  async function mutate(endpoint: string, method: string, body?: unknown) {
    busy = true;
    error = "";
    message = "";
    try {
      await api(endpoint, {
        method,
        ...(body ? { body: JSON.stringify(body) } : {}),
      });
      await refresh();
      await load(view, tick);
      message = "Workspace updated.";
      return true;
    } catch (e) {
      error = (e as Error).message;
      return false;
    } finally {
      busy = false;
    }
  }
</script>

<section class="management-page">
  <header class="page-heading">
    <p class="breadcrumb">Workspace / {view}</p>
    <h1>
      {view === "Sources"
        ? "Your sources"
        : view === "Activity"
          ? "Workspace activity"
          : "Workspace settings"}
    </h1>
    <p>
      {view === "Sources"
        ? "The documents behind your research. Add files or directories; Graf keeps the originals untouched."
        : view === "Activity"
          ? "Follow each processing stage, from source discovery to a published collection."
          : "A local workspace, connected on your terms."}
    </p>
  </header>
  {#if error}<p class="notice error" role="alert">
      {error}
    </p>{/if}{#if message}<p role="status" class="notice">{message}</p>{/if}
  {#if view === "Sources"}
    <div class="source-overview">
      <div>
        <span>COLLECTION</span><strong
          >{status.counts.documents ?? 0}<small>documents</small></strong
        >
      </div>
      <div>
        <span>EXTRACTION</span><strong
          >{status.counts.passages ?? 0}<small>passages</small></strong
        >
      </div>
      <div>
        <span>READINESS</span><strong class="readiness-word"
          >{status.state.replaceAll("_", " ")}<small>{status.phase}</small
          ></strong
        >
      </div>
    </div>
    <form
      class="add-source"
      on:submit|preventDefault={async () => {
        if (await mutate("/sources", "POST", { path })) path = "";
      }}
    >
      <label for="source-path">File or directory path</label>
      <div class="row">
        <input
          id="source-path"
          required
          bind:value={path}
          placeholder="/absolute/path/to/source"
        /><button class="primary" disabled={busy || !path.trim()}
          ><span aria-hidden="true">＋</span> Add source</button
        >
      </div>
    </form>
    <details>
      <summary>Allowed locations</summary
      >{#each sources?.allowed_roots || [] as root}<code class="block"
          >{root}</code
        >{/each}{#if sources?.allowed_roots.length === 0}<p>
          No locations configured. Update the local workspace configuration.
        </p>{/if}
    </details>
    <div class="section-heading">
      <h2>Registered sources</h2>
      <span>{sources?.items.length ?? "—"}</span>
    </div>
    {#if !sources && !error}<p role="status">Loading sources…</p>{/if}
    {#if sources?.items.length === 0}<div class="empty">
        <h3>Start with your first source</h3>
        <p>
          Add an allowed file or directory above to build your evidence
          workspace.
        </p>
      </div>{/if}
    <div class="table-scroll">
      <table class="source-table">
        <thead
          ><tr
            ><th>Source</th><th>Type</th><th>Status</th><th>Files</th><th
              >Controls</th
            ></tr
          ></thead
        ><tbody
          >{#each sources?.items || [] as s}<tr
              ><td
                ><strong>{s.path.split("/").pop()}</strong><small class="path"
                  >{s.path}</small
                >{#if s.error}<p class="error">{s.error}</p>{/if}</td
              ><td>{s.kind}</td><td
                ><span class="source-status"
                  ><i class="state-dot"></i>{s.status}</span
                ></td
              ><td>{s.file_count}</td><td
                ><div class="row">
                  <button
                    disabled={busy}
                    aria-label={`Rescan ${s.path}`}
                    on:click={() =>
                      mutate(
                        `/sources/${encodeURIComponent(s.id)}/rescan`,
                        "POST",
                      )}>Rescan</button
                  ><label class="check"
                    ><input
                      type="checkbox"
                      checked={s.enabled}
                      disabled={busy}
                      on:change={(e) =>
                        mutate(
                          `/sources/${encodeURIComponent(s.id)}`,
                          "PATCH",
                          { enabled: e.currentTarget.checked },
                        )}
                    />Enabled</label
                  ><button
                    class="text-button"
                    aria-label={`Remove ${s.path}`}
                    disabled={busy}
                    on:click={() => (remove = s)}>Remove</button
                  >
                </div></td
              ></tr
            >{/each}</tbody
        >
      </table>
    </div>
    <div class="source-note">
      <span>↳</span>
      <p>
        Removing a source changes the current collection. Historical session
        evidence is retained until explicitly erased through its audit workflow.
      </p>
    </div>
    {#if remove}<dialog
        bind:this={confirmDialog}
        on:cancel={() => (remove = null)}
        aria-labelledby="remove-title"
      >
        <h2 id="remove-title">Remove this source?</h2>
        <p>{remove.path}</p>
        <p>
          This removes it from current evidence. Original files are preserved;
          historical audit evidence is retained.
        </p>
        {#if error}<p role="alert">{error}</p>{/if}
        <div class="row">
          <button on:click={() => (remove = null)}>Cancel</button><button
            class="danger"
            disabled={busy}
            on:click={async () => {
              if (
                await mutate(
                  `/sources/${encodeURIComponent(remove!.id)}`,
                  "DELETE",
                )
              )
                remove = null;
            }}>Remove source</button
          >
        </div>
      </dialog>{/if}
  {:else if view === "Activity"}
    {#each jobs || [] as j}<article class="job-row">
        <div class="job-heading">
          <h2>{j.phase || "Queued"}</h2>
          <span>{j.state}</span>
        </div>
        <p class="muted">
          {j.started_at
            ? new Date(j.started_at).toLocaleString()
            : "Not started"}{j.finished_at
            ? ` → ${new Date(j.finished_at).toLocaleString()}`
            : ""}
        </p>
        <code>{j.id}</code>{#if j.progress != null}<pre>{typeof j.progress ===
            "string"
              ? j.progress
              : JSON.stringify(j.progress, null, 2)}</pre>{/if}{#if j.error}<p
            class="error"
          >
            {j.error}
          </p>{/if}
      </article>{:else}<p class="empty">
        {jobs
          ? "No jobs yet. Add a source to get started."
          : "Loading activity…"}
      </p>{/each}
  {:else}
    <section class="settings-section">
      <h2>Codex connection</h2>
      <p>Codex may send selected evidence to its configured model provider.</p>
      {#if typeof settings?.codex_instructions === "string"}<pre>{settings.codex_instructions}</pre>
        <button
          on:click={async () => {
            try {
              await navigator.clipboard.writeText(
                String(settings?.codex_instructions),
              );
              message = "Instructions copied.";
            } catch {
              error =
                "Clipboard unavailable. Select and copy the instructions above.";
            }
          }}>Copy instructions</button
        >{:else}<p class="muted">
          {settings
            ? "Connection instructions are not available from this server."
            : "Loading configuration…"}
        </p>{/if}
    </section>
    {#if settings}<section class="settings-section">
        <h2>Configuration</h2>
        <dl class="settings">
          {#each Object.entries(settings).filter(([k]) => k !== "codex_instructions") as [k, v]}<div
            >
              <dt>{k.replaceAll("_", " ")}</dt>
              <dd>
                <pre>{typeof v === "string"
                    ? v
                    : JSON.stringify(v, null, 2)}</pre>
              </dd>
            </div>{/each}
        </dl>
      </section>{/if}
    <section class="settings-section">
      <h2>Workspace controls</h2>
      <div class="row">
        <button disabled={busy} on:click={() => mutate("/rebuild", "POST")}
          >Rebuild evidence index</button
        ><button on:click={logout}>End session</button>
      </div>
    </section>
    <section class="settings-section">
      <h2>Graph library</h2>
      <p>
        Cosmograph by cosmograph-org · Non-commercial use under CC BY-NC 4.0.
      </p>
      <a href="/cosmograph-license.txt" target="_blank" rel="noreferrer"
        >Bundled license and attribution ↗</a
      >
    </section>
  {/if}
</section>

// product/ui/src/Management.tsx
import { useEffect, useState, useRef } from "react";
import { api, Source, Job } from "./api";
import { Plus, RefreshCw, Trash2, Copy } from "lucide-react";
function Confirm({
  children,
  onCancel,
}: {
  children: React.ReactNode;
  onCancel: () => void;
}) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => {
    ref.current?.showModal();
    return () => ref.current?.close();
  }, []);
  return (
    <dialog
      ref={ref}
      className="confirm"
      onCancel={onCancel}
      aria-labelledby="remove-title"
    >
      {children}
    </dialog>
  );
}
export function Sources({
  tick,
  mutate,
  busy,
  mutationError,
}: {
  tick: number;
  mutate: (path: string, init: RequestInit) => Promise<boolean>;
  busy: boolean;
  mutationError?: string;
}) {
  const [data, setData] = useState<{
    items: Source[];
    allowed_roots: string[];
  }>();
  const [error, setError] = useState("");
  const [path, setPath] = useState("");
  const [remove, setRemove] = useState<Source | null>(null);
  useEffect(() => {
    let alive = true;
    api<{ items: Source[]; allowed_roots: string[] }>("/sources")
      .then((x) => {
        if (alive) {
          setData(x);
          setError("");
        }
      })
      .catch((e) => {
        if (alive) {
          setData(undefined);
          setError(e.message);
        }
      });
    return () => {
      alive = false;
    };
  }, [tick]);
  return (
    <section className="page">
      <h2>Your sources</h2>
      <p className="muted">
        Add a file or directory from an allowed location. Originals stay
        untouched.
      </p>
      <form
        className="add-source"
        onSubmit={async (e) => {
          e.preventDefault();
          if (
            await mutate("/sources", {
              method: "POST",
              body: JSON.stringify({ path }),
            })
          )
            setPath("");
        }}
      >
        <label htmlFor="source-path">File or directory path</label>
        <div className="row">
          <input
            id="source-path"
            value={path}
            onChange={(e) => setPath(e.target.value)}
            placeholder="/absolute/path/to/source"
            required
          />
          <button className="primary" disabled={busy || !path.trim()}>
            <Plus size={17} />
            Add source
          </button>
        </div>
      </form>
      <details>
        <summary>Allowed locations</summary>
        {data?.allowed_roots.map((x) => (
          <code className="block" key={x}>
            {x}
          </code>
        ))}
        {data?.allowed_roots.length === 0 && (
          <p>
            No locations configured. Update the local workspace configuration.
          </p>
        )}
      </details>
      {error && <p role="alert">{error}</p>}
      {!data && !error && <p role="status">Loading sources…</p>}
      {data?.items.length === 0 && (
        <div className="empty">
          <h3>Start with your first source</h3>
          <p>
            Choose an allowed file or directory above to build your local
            evidence workspace.
          </p>
        </div>
      )}
      <div className="source-table-wrap">
        <table className="source-table">
          <thead>
            <tr>
              <th>Source</th>
              <th>Type</th>
              <th>Status</th>
              <th>Files</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {data?.items.map((s) => (
              <tr key={s.id}>
                <td>
                  <strong>{s.path}</strong>
                  {s.error && <p className="error">{s.error}</p>}
                </td>
                <td>{s.kind}</td>
                <td>
                  <span className={`source-status ${s.status}`}>
                    {s.status}
                  </span>
                </td>
                <td>{s.file_count}</td>
                <td>
                  <div className="row">
                    <button
                      disabled={busy}
                      onClick={() =>
                        void mutate(
                          `/sources/${encodeURIComponent(s.id)}/rescan`,
                          { method: "POST" },
                        )
                      }
                      aria-label={`Rescan ${s.path}`}
                    >
                      <RefreshCw size={16} />
                      Rescan
                    </button>
                    <label className="toggle">
                      <input
                        type="checkbox"
                        checked={s.enabled}
                        disabled={busy}
                        onChange={(e) =>
                          void mutate(`/sources/${encodeURIComponent(s.id)}`, {
                            method: "PATCH",
                            body: JSON.stringify({ enabled: e.target.checked }),
                          })
                        }
                      />
                      Enabled
                    </label>
                    <button
                      className="remove-source"
                      disabled={busy}
                      onClick={() => setRemove(s)}
                      aria-label={`Remove ${s.path}`}
                    >
                      <Trash2 size={16} />
                      Remove
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {remove && (
        <Confirm onCancel={() => setRemove(null)}>
          <h3 id="remove-title">Remove this source?</h3>
          {mutationError && (
            <p className="error" role="alert">
              {mutationError}
            </p>
          )}
          <p>{remove.path}</p>
          <p>
            This removes it from current evidence. Original files are preserved;
            historical audit evidence is retained.
          </p>
          <div className="row">
            <button autoFocus onClick={() => setRemove(null)}>
              Cancel
            </button>
            <button
              className="danger"
              disabled={busy}
              onClick={async () => {
                if (
                  await mutate(`/sources/${encodeURIComponent(remove.id)}`, {
                    method: "DELETE",
                  })
                )
                  setRemove(null);
              }}
            >
              Remove source
            </button>
          </div>
        </Confirm>
      )}
    </section>
  );
}
export function Activity({ tick }: { tick: number }) {
  const [jobs, setJobs] = useState<Job[]>();
  const [error, setError] = useState("");
  useEffect(() => {
    let alive = true;
    api<{ items: Job[] }>("/jobs")
      .then((x) => {
        if (alive) {
          setJobs(x.items);
          setError("");
        }
      })
      .catch((e) => {
        if (alive) {
          setJobs(undefined);
          setError(e.message);
        }
      });
    return () => {
      alive = false;
    };
  }, [tick]);
  return (
    <section className="page">
      <h2>Workspace activity</h2>
      <p className="muted">
        Actual processing stages and results from your local workspace.
      </p>
      {error && <p role="alert">{error}</p>}
      {!jobs && !error && <p>Loading activity…</p>}
      {jobs?.length === 0 && (
        <div className="empty">No jobs yet. Add a source to get started.</div>
      )}
      {jobs?.map((j) => (
        <article className="source-row" key={j.id}>
          <div>
            <h3>{j.phase || "Queued"}</h3>
            <p>{j.state}</p>
            <small className="muted">
              {j.started_at
                ? new Date(j.started_at).toLocaleString()
                : "Not started"}
              {j.finished_at
                ? ` → ${new Date(j.finished_at).toLocaleString()}`
                : ""}
            </small>
            {j.progress != null && (
              <pre>
                {typeof j.progress === "string"
                  ? j.progress
                  : JSON.stringify(j.progress, null, 2)}
              </pre>
            )}
            {j.error && <p className="error">{j.error}</p>}
          </div>
          <code>{j.id}</code>
        </article>
      ))}
    </section>
  );
}
export function Settings({ codex = false }: { codex?: boolean }) {
  const [settings, setSettings] = useState<Record<string, unknown>>();
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  useEffect(() => {
    api<Record<string, unknown>>("/settings")
      .then(setSettings)
      .catch((e) => setError(e.message));
  }, []);
  const instructions =
    typeof settings?.codex_instructions === "string"
      ? settings.codex_instructions
      : "";
  return (
    <section className="page">
      <h2>{codex ? "Use Graf in Codex" : "Workspace settings"}</h2>
      <p className="muted">Your local workspace, connected on your terms.</p>
      {error && <p role="alert">{error}</p>}
      {!settings && !error && <p>Loading configuration…</p>}
      <h3>Codex connection</h3>
      <p className="muted">
        Codex may send selected evidence to its configured model provider.
        Review its settings before querying private documents.
      </p>
      {instructions ? (
        <>
          <pre className="instructions">{instructions}</pre>
          <button
            onClick={async () => {
              try {
                await navigator.clipboard.writeText(instructions);
                setCopied(true);
              } catch {
                setError(
                  "Clipboard unavailable. Select and copy the instructions above.",
                );
              }
            }}
          >
            <Copy size={16} />
            {copied ? "Copied" : "Copy instructions"}
          </button>
        </>
      ) : (
        settings && (
          <p>
            Connection instructions are not available from this server. Check
            the local installation documentation.
          </p>
        )
      )}
      {!codex && settings && (
        <>
          <h3>Safe configuration</h3>
          <dl className="settings">
            {Object.entries(settings)
              .filter(([k]) => k !== "codex_instructions")
              .map(([k, v]) => (
                <div key={k}>
                  <dt>{k.replaceAll("_", " ")}</dt>
                  <dd>
                    <pre>
                      {typeof v === "string" ? v : JSON.stringify(v, null, 2)}
                    </pre>
                  </dd>
                </div>
              ))}
          </dl>
          <h3>Graph library</h3>
          <p>
            Cosmograph by cosmograph-org · Non-commercial use under CC BY-NC
            4.0.
          </p>
          <a href="/cosmograph-license.txt" target="_blank" rel="noreferrer">
            Read bundled license and attribution
          </a>
        </>
      )}
    </section>
  );
}
